# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceIdentification.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FaceIdentification(object):
    def setupUi(self, FaceIdentification):
        FaceIdentification.setObjectName("FaceIdentification")
        FaceIdentification.resize(906, 601)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        FaceIdentification.setFont(font)
        self.centralwidget = QtWidgets.QWidget(FaceIdentification)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.recordFace = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.recordFace.setFont(font)
        self.recordFace.setObjectName("recordFace")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.recordFace)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.faceName = QtWidgets.QLabel(self.recordFace)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.faceName.setFont(font)
        self.faceName.setObjectName("faceName")
        self.gridLayout_2.addWidget(self.faceName, 0, 0, 1, 1)
        self.faceNameEdit = QtWidgets.QLineEdit(self.recordFace)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.faceNameEdit.setFont(font)
        self.faceNameEdit.setObjectName("faceNameEdit")
        self.gridLayout_2.addWidget(self.faceNameEdit, 0, 1, 1, 1)
        self.tipsForName = QtWidgets.QLabel(self.recordFace)
        self.tipsForName.setObjectName("tipsForName")
        self.gridLayout_2.addWidget(self.tipsForName, 1, 1, 1, 1)
        self.pickFaceNum = QtWidgets.QLabel(self.recordFace)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pickFaceNum.setFont(font)
        self.pickFaceNum.setObjectName("pickFaceNum")
        self.gridLayout_2.addWidget(self.pickFaceNum, 2, 0, 1, 1)
        self.faceNumEdit = QtWidgets.QLineEdit(self.recordFace)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.faceNumEdit.setFont(font)
        self.faceNumEdit.setObjectName("faceNumEdit")
        self.gridLayout_2.addWidget(self.faceNumEdit, 2, 1, 1, 1)
        self.tipsForFaceNum = QtWidgets.QLabel(self.recordFace)
        self.tipsForFaceNum.setObjectName("tipsForFaceNum")
        self.gridLayout_2.addWidget(self.tipsForFaceNum, 3, 1, 1, 1)
        self.successTips = QtWidgets.QLabel(self.recordFace)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.successTips.setFont(font)
        self.successTips.setText("")
        self.successTips.setObjectName("successTips")
        self.gridLayout_2.addWidget(self.successTips, 4, 0, 2, 1)
        self.viewFaceData = QtWidgets.QPushButton(self.recordFace)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.viewFaceData.setFont(font)
        self.viewFaceData.setObjectName("viewFaceData")
        self.gridLayout_2.addWidget(self.viewFaceData, 4, 1, 1, 1)
        self.allFaceData = QtWidgets.QTextEdit(self.recordFace)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.allFaceData.setFont(font)
        self.allFaceData.setObjectName("allFaceData")
        self.gridLayout_2.addWidget(self.allFaceData, 5, 1, 1, 1)
        self.recordStart = QtWidgets.QPushButton(self.recordFace)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.recordStart.setFont(font)
        self.recordStart.setObjectName("recordStart")
        self.gridLayout_2.addWidget(self.recordStart, 6, 0, 1, 2)
        self.gridLayout.addWidget(self.recordFace, 0, 0, 2, 1)
        self.trainFace = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.trainFace.setFont(font)
        self.trainFace.setObjectName("trainFace")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.trainFace)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tipsForTrain = QtWidgets.QLabel(self.trainFace)
        self.tipsForTrain.setObjectName("tipsForTrain")
        self.gridLayout_3.addWidget(self.tipsForTrain, 0, 0, 1, 1)
        self.trainStart = QtWidgets.QPushButton(self.trainFace)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.trainStart.setFont(font)
        self.trainStart.setObjectName("trainStart")
        self.gridLayout_3.addWidget(self.trainStart, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.trainFace, 0, 1, 1, 1)
        self.identifyFace = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.identifyFace.setFont(font)
        self.identifyFace.setObjectName("identifyFace")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.identifyFace)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.identifyFace)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.identifyStart = QtWidgets.QPushButton(self.identifyFace)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.identifyStart.setFont(font)
        self.identifyStart.setObjectName("identifyStart")
        self.gridLayout_4.addWidget(self.identifyStart, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.identifyFace, 1, 1, 1, 1)
        FaceIdentification.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(FaceIdentification)
        self.statusbar.setObjectName("statusbar")
        FaceIdentification.setStatusBar(self.statusbar)

        self.retranslateUi(FaceIdentification)
        QtCore.QMetaObject.connectSlotsByName(FaceIdentification)
        FaceIdentification.setTabOrder(self.faceNameEdit, self.recordStart)
        FaceIdentification.setTabOrder(self.recordStart, self.trainStart)
        FaceIdentification.setTabOrder(self.trainStart, self.identifyStart)

    def retranslateUi(self, FaceIdentification):
        _translate = QtCore.QCoreApplication.translate
        FaceIdentification.setWindowTitle(_translate("FaceIdentification", "MainWindow"))
        self.recordFace.setTitle(_translate("FaceIdentification", "记录人脸信息"))
        self.faceName.setText(_translate("FaceIdentification", "面部名称："))
        self.tipsForName.setText(_translate("FaceIdentification", "只能输入英文名称！"))
        self.pickFaceNum.setText(_translate("FaceIdentification", "采集数量："))
        self.tipsForFaceNum.setText(_translate("FaceIdentification", "建议为0到1000!数量越多，训练时间越长！"))
        self.viewFaceData.setText(_translate("FaceIdentification", "查看当前已采集的面部数据文件"))
        self.recordStart.setText(_translate("FaceIdentification", "开始记录"))
        self.trainFace.setTitle(_translate("FaceIdentification", "训练人脸数据集"))
        self.tipsForTrain.setText(_translate("FaceIdentification", "所有人脸信息记录完成后再进行训练！"))
        self.trainStart.setText(_translate("FaceIdentification", "开始训练"))
        self.identifyFace.setTitle(_translate("FaceIdentification", "识别人脸"))
        self.label.setText(_translate("FaceIdentification", "训练结束后即可开始识别！\n"
"\n"
"按Q键停止识别！！！"))
        self.identifyStart.setText(_translate("FaceIdentification", "开始识别"))
